on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test the action locally
    steps:
      - name: Check if checklist items are completed
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          requireChecklist: true
          onlyCheckBody: true

